#define CONNECTION_CALLBACK(name) void name(uint32_t type, void *data, size_t data_length, void *context, int cid)
typedef CONNECTION_CALLBACK(connection_callback);

static mach_port_t (* CGSGetConnectionPortById)(int);
static int64_t (* SLSPerformAsynchronousBridgedWindowManagementOperation)(void *);
extern mach_port_t mig_get_special_reply_port(void);
extern AXUIElementRef _AXUIElementCreateWithRemoteToken(CFDataRef data);
extern AXError _AXUIElementGetWindow(AXUIElementRef ref, uint32_t *wid);
extern int SLSMainConnectionID(void);
extern CGError SLSNewConnection(int zero, int *cid);
extern CGError SLSReleaseConnection(int cid);
extern CGError SLSRegisterConnectionNotifyProc(int cid, connection_callback *handler, uint32_t event, void *context);
extern CGError SLSGetWindowBounds(int cid, uint32_t wid, CGRect *frame);
extern CGError SLSGetWindowLevel(int cid, uint32_t wid, int *level);
extern int SLSGetWindowSubLevel(int cid, uint32_t wid);
extern CGError SLSGetWindowAlpha(int cid, uint32_t wid, float *alpha);
extern CGError SLSSetWindowAlpha(int cid, uint32_t wid, float alpha);
extern CGError SLSSetWindowResolution(int cid, uint32_t wid, double resolution);
extern CGError SLSCopyWindowProperty(int cid, uint32_t wid, CFStringRef property, CFTypeRef *value);
extern CFStringRef SLSCopyManagedDisplayForWindow(int cid, uint32_t wid);
extern CFStringRef SLSCopyBestManagedDisplayForRect(int cid, CGRect rect);
extern CFArrayRef SLSCopySpacesForWindows(int cid, int selector, CFArrayRef window_list);
extern CGError SLSDisableUpdate(int cid);
extern CGError SLSReenableUpdate(int cid);
extern CGError SLSNewWindow(int cid, int type, float x, float y, CFTypeRef region, uint32_t *wid);
extern CGError SLSNewWindowWithOpaqueShapeAndContext(int cid, int type, CFTypeRef region, CFTypeRef opaque_shape, int options, uint64_t *tags, float x, float y, int tag_size, uint32_t *wid, void *context);
extern CGError SLSReleaseWindow(int cid, uint32_t wid);
extern CGError SLSSetWindowTags(int cid, uint32_t wid, uint64_t *tags, int tag_size);
extern CGError SLSClearWindowTags(int cid, uint32_t wid, uint64_t *tags, int tag_size);
extern CGError SLSSetWindowShape(int cid, uint32_t wid, float x_offset, float y_offset, CFTypeRef shape);
extern CGError SLSSetWindowOpacity(int cid, uint32_t wid, bool opaque);
extern CGError SLSSetWindowBackgroundBlurRadiusStyle(int cid, uint32_t wid, int radius, int style);
extern CGError SLSOrderWindow(int cid, uint32_t wid, int mode, uint32_t rel_wid);
extern CGError SLSWindowIsOrderedIn(int cid, uint32_t wid, uint8_t *value);
extern CGError SLSSetWindowLevel(int cid, uint32_t wid, int level);
extern CGError SLSSetWindowSubLevel(int cid, uint32_t wid, int sub_level);
extern CGContextRef SLWindowContextCreate(int cid, uint32_t wid, CFDictionaryRef options);
extern CFTypeRef CGRegionCreateEmptyRegion(void);
extern CGError CGSNewRegionWithRect(CGRect *rect, CFTypeRef *region);
extern CFUUIDRef CGDisplayCreateUUIDFromDisplayID(uint32_t did);
extern CFArrayRef SLSCopyManagedDisplays(int cid);
extern uint64_t SLSManagedDisplayGetCurrentSpace(int cid, CFStringRef uuid);
extern CFStringRef SLSCopyActiveMenuBarDisplayIdentifier(int cid);
// 3rd arg is a uint64 EVENT TIMESTAMP, not a second uuid: the server clamps it
// to _SLSCurrentEventTimestamp() then drops the call if it is older than the
// last stored stamp. Pass ~0ULL so it always clamps to "now".
extern CGError SLSSetActiveMenuBarDisplayIdentifier(int cid, CFStringRef uuid, uint64_t event_time);
extern CFStringRef SLSCopyBestManagedDisplayForPoint(int cid, CGPoint point);
extern bool SLSManagedDisplayIsAnimating(int cid, CFStringRef uuid);
extern CGError SLSSetMenuBarInsetAndAlpha(int cid, double unused1, double unused2, float alpha);
extern CGError SLSGetMenuBarAutohideEnabled(int cid, int *enabled);
extern CGError SLSGetRevealedMenuBarBounds(CGRect *rect, int cid, uint64_t sid);
extern CGError SLSGetDisplayMenubarHeight(uint32_t did, uint32_t *height);
extern CGError SLSGetDockRectWithReason(int cid, CGRect *rect, int *reason);
extern Boolean CoreDockGetAutoHideEnabled(void);
extern void CoreDockGetOrientationAndPinning(int *orientation, int *pinning);
extern CFStringRef SLSCopyManagedDisplayForSpace(int cid, uint64_t sid);
extern CGError SLSSpaceSetFrontPSN(int cid, uint64_t sid, ProcessSerialNumber psn);
extern int SLSSpaceGetType(int cid, uint64_t sid);
extern CFStringRef SLSSpaceCopyName(int cid, uint64_t sid);
extern CFArrayRef SLSCopyWindowsWithOptionsAndTags(int cid, uint32_t owner, CFArrayRef spaces, uint32_t options, uint64_t *set_tags, uint64_t *clear_tags);
extern int SLSGetSpaceManagementMode(int cid);
extern CFArrayRef SLSCopyManagedDisplaySpaces(int cid);
extern CGError SLSProcessAssignToSpace(int cid, pid_t pid, uint64_t sid);
extern CGError SLSProcessAssignToAllSpaces(int cid, pid_t pid);
extern void SLSMoveWindowsToManagedSpace(int cid, CFArrayRef window_list, uint64_t sid);
extern CGError CoreDockSendNotification(CFStringRef notification, int unknown);
extern CGError SLSMoveWindow(int cid, uint32_t wid, CGPoint *point);
extern CFArrayRef SLSCopyAssociatedWindows(int cid, uint32_t wid);
extern CFTypeRef SLSWindowQueryWindows(int cid, CFArrayRef windows, int count);
extern CFTypeRef SLSWindowQueryResultCopyWindows(CFTypeRef window_query);
extern int SLSWindowIteratorGetCount(CFTypeRef iterator);
extern bool SLSWindowIteratorAdvance(CFTypeRef iterator);
extern uint32_t SLSWindowIteratorGetParentID(CFTypeRef iterator);
extern uint32_t SLSWindowIteratorGetWindowID(CFTypeRef iterator);
extern uint64_t SLSWindowIteratorGetTags(CFTypeRef iterator);
extern uint64_t SLSWindowIteratorGetAttributes(CFTypeRef iterator);
extern int SLSWindowIteratorGetLevel(CFTypeRef iterator);
extern OSStatus _SLPSGetFrontProcess(ProcessSerialNumber *psn);
extern CGError SLSGetWindowOwner(int cid, uint32_t wid, int *wcid);
extern CGError SLSGetConnectionPSN(int cid, ProcessSerialNumber *psn);
extern CGError SLSConnectionGetPID(int cid, pid_t *pid);
extern CGError SLSGetConnectionIDForPSN(int cid, ProcessSerialNumber *psn, int *psn_cid);
extern CGError _SLPSSetFrontProcessWithOptions(ProcessSerialNumber *psn, uint32_t wid, uint32_t mode);
extern CGError SLPSPostEventRecordTo(ProcessSerialNumber *psn, uint8_t *bytes);
extern OSStatus SLSFindWindowAndOwner(int cid, int zero, int one, int zero_again, CGPoint *screen_point, CGPoint *window_point, uint32_t *wid, int *wcid);
extern CGError SLSGetCurrentCursorLocation(int cid, CGPoint *point);
extern CGError SLSWindowSetShadowProperties(uint32_t wid, CFDictionaryRef options);
extern CGError SLSRequestNotificationsForWindows(int cid, uint32_t *window_list, int window_count);
extern CGError SLSSetWindowTransform(int cid, uint32_t wid, CGAffineTransform t);
extern CFTypeRef SLSTransactionCreate(int cid);
extern CGError SLSTransactionCommit(CFTypeRef transaction, int synchronous);
extern CGError SLSTransactionSetWindowTransform(CFTypeRef transaction, uint32_t wid, int unknown, int unknown2, CGAffineTransform t);
extern CGError SLSTransactionOrderWindow(CFTypeRef transaction, uint32_t wid, int order, uint32_t rel_wid);
extern CGError SLSTransactionOrderWindowGroup(CFTypeRef transaction, uint32_t wid, int order, uint32_t rel_wid);
extern CGError SLSTransactionSetWindowAlpha(CFTypeRef transaction, uint32_t wid, float alpha);
extern CGError SLSTransactionSetWindowSystemAlpha(CFTypeRef transaction, uint32_t wid, float alpha);
extern CFArrayRef SLSHWCaptureWindowList(int cid, uint32_t *window_list, int window_count, uint32_t options);
extern CGError SLSSpaceSetCompatID(int cid, uint64_t sid, int workspace);
extern CGError SLSSetWindowListWorkspace(int cid, uint32_t *window_list, int window_count, int workspace);

// ── non-upstream SPIs: animation engine + dependencies ──
extern void mig_dealloc_special_reply_port(mach_port_t port);
extern uint64_t SLSGetActiveSpace(int cid);
extern int _CGSDefaultConnection(void);
extern CGError SLSRegisterNotifyProc(void* handler, uint32_t event, void* context);
extern CGError SLSPackagesEnableConnectionOcclusionNotifications(int cid, bool enable, bool *out_prev);
extern CGError SLSPackagesEnableConnectionWindowModificationNotifications(int cid, bool enable, bool *out_prev);
extern CGError SLSPackagesEnableWindowOcclusionNotifications(int cid, uint32_t wid, bool enable, bool *out_prev);
extern CGError SLPSModifyConnectionNotifications(int cid, uint32_t notifications, uint32_t mask, uint32_t *out_prev);
extern CGError SLSGetUserAccessibilityReport(int cid, pid_t pid, CFDictionaryRef *report_out);
extern CGError SLSGetUserAccessibilityReportForPid(pid_t pid, CFDictionaryRef *report_out);
extern CGError SLSGetSystemWindow(int cid, int which, uint32_t *out_wid);
extern CGError SLSGetSystemBackgroundWindow(int cid, int which, uint32_t *out_wid);
extern CGError SLSGetScreenRectForWindow(int cid, uint32_t wid, CGRect *out);
extern CGError SLSGetWindowTransform(int cid, uint32_t wid, CGAffineTransform *out);
extern CGError SLSGetWindowType(int cid, uint32_t wid, int *type_out);
extern CGError SLSSetWindowProperty(int cid, uint32_t wid, CFStringRef property, CFTypeRef value);
extern void SLSTransactionWait(CFTypeRef transaction);
extern CGError SLSGetWindowOpacity(int cid, uint32_t wid, uint8_t *opaque);
extern CGError SLSWindowIsVisible(int cid, uint32_t wid, uint8_t *value);
extern CFTypeRef SLSManagedDisplayQueryDisplays(int cid, CFArrayRef displays, int count);
extern CFTypeRef SLSManagedDisplayQueryResultCopyDisplays(CFTypeRef display_query);
extern int SLSManagedDisplayIteratorGetCount(CFTypeRef iterator);
extern bool SLSManagedDisplayIteratorAdvance(CFTypeRef iterator);
extern CFTypeID SLSManagedDisplayIteratorGetTypeID(CFTypeRef iterator);
extern uint64_t SLSManagedDisplayIteratorGetAttributes(CFTypeRef iterator);
extern CGRect SLSManagedDisplayIteratorGetBounds(CFTypeRef iterator);
extern CFUUIDBytes SLSManagedDisplayIteratorGetUUIDBytes(CFTypeRef iterator);
extern CFTypeRef SLSManagedDisplayIteratorCopyRoleWindows(CFTypeRef iterator);
extern CFTypeRef SLSManagedDisplayIteratorCopyManagedSpaces(CFTypeRef iterator);
extern CFArrayRef SLSManagedDisplaysCopyRoleWindows(int cid, CFArrayRef display_uuids, uint64_t role);
extern int SLSGetDisplayList(int max_count, uint32_t *display_list, int *out_count);
extern int SLSGetPotentiallyActiveDisplayList(int max_count, uint32_t *display_list, int *out_count);
extern int SLSGetActiveDisplayList(int max_count, uint32_t *display_list, int *out_count);
extern CGError SLSManagedDisplaySetIsAnimating(int cid, CFStringRef uuid, bool is_animating);
extern CGError SLSSetMenuBarSystemOverrideAlpha(int cid, CFStringRef display_uuid, float alpha);
extern CGError SLSResetMenuBarSystemOverrideAlphas(int cid);
extern uint64_t SLSSpaceCreate(int cid, int options, CFDictionaryRef values);
extern void SLSSpaceDestroy(int cid, uint64_t sid);
extern void SLSMoveManagedSpaceToDisplayIndex(int cid, uint64_t sid, CFStringRef display_uuid, uint64_t index);
extern int CGSSpaceGetType(int cid, uint64_t sid);
extern CFArrayRef SLSCopyWindowsWithOptionsAndTagsAndSpaceOptions(int cid, uint32_t owner, uint64_t spaceOptions, uint32_t options, uint64_t *set_tags, uint64_t *clear_tags);
extern CGError SLSGetWindowList(int cid, int target_cid, int capacity, uint32_t *list_out, int *count_out);
extern CGError SLSGetOnScreenWindowList(int cid, int target_cid, int capacity, uint32_t *list_out, int *count_out);
extern void SLSGetWindowListWithTags(int cid, int target_cid, int capacity, uint32_t *list_out, int *count_out, int onscreen_only, uint64_t *set_tags, uint64_t *clear_tags, int tag_size);
extern CGRect   SLSSpaceGetRect(int cid, uint64_t sid);
extern CGSize   SLSSpaceGetInterTileSpacing(int cid, uint64_t sid);
extern uint32_t SLSGetTileSpaceDividerDirections(uint64_t sid);
extern CFArrayRef SLSSpaceCopyTileSpaces(int cid, uint64_t sid);
extern CGRect   SLSWindowGetTileRect(int cid, uint32_t wid);
extern int      SLSSpaceGetSpacersAtPoint(int cid, uint64_t sid,
                                          uint32_t *out_v_idx, uint32_t *out_h_idx,
                                          CGRect *out_rect, CGPoint point);
extern CGAffineTransform SLSSpaceGetTransform(int cid, uint64_t sid, int *options);
extern uint64_t   SLSSpaceWithName(int cid, CFStringRef name);
extern float      SLSSpaceGetAlpha(int cid, uint64_t sid);
extern int        SLSSpaceGetAbsoluteLevel(int cid, uint64_t sid);
extern int        SLSSpaceGetCompatID(int cid, uint64_t sid);         /* dead stub — always returns 0 */
extern CFArrayRef SLSSpaceCopyOwners(int cid, uint64_t sid);          /* CFArray<NSNumber*> of owning pids; caller releases */

extern CFArrayRef SLSCopyManagedDisplaySpaces(int cid);
extern int SLSCopyWindowGroup(int cid, uint32_t wid, CFStringRef groupKind, void **outBuf, int32_t *outCount);
extern int SLSGetWindowDepth(int cid, uint32_t wid);
extern void *SLSGetWindowLayerContext(int cid, uint32_t wid);
extern void SLSGetSpaceBindings(uint32_t wid, int8_t *outByte, uint64_t *outSpaceID);
extern uint64_t SLSWindowGetBestSpace(uint32_t wid, uint32_t index);
extern CFTypeID SLSWindowQueryResultGetTypeID(CFTypeRef window_query_result);
extern CFTypeID SLSWindowQueryGetTypeID(CFTypeRef window_query);
extern CFTypeRef SLSWindowQueryCreate(CFDictionaryRef initial_values);
extern void SLSWindowQuerySetValue(CFTypeRef window_query, CFStringRef key, CFTypeRef value);
extern CFTypeRef SLSWindowQueryCopyValue(CFTypeRef window_query, CFStringRef key);
extern CFTypeRef SLSWindowQueryRun(int cid, CFTypeRef window_query, int flags);
extern int SLSWindowQueryResultGetWindowCount(CFTypeRef window_query_result);
extern int SLSPackagesGetWorkspaceForWorkspaceIdentifier(int cid, CFStringRef identifier);
extern int SLSGetWindowCount(int32_t cid_or_unused, uint32_t selector, int32_t *out_count);
extern int SLSWindowQueryResultGetSpaceCount(CFTypeRef window_query);
extern CFTypeRef SLSWindowQueryResultCopySpaces(CFTypeRef window_query);
extern int SLSWindowQueryResultGetManagedDisplayCount(CFTypeRef window_query_result);
extern CFArrayRef SLSWindowQueryResultCopyManagedDisplays(CFTypeRef window_query_result);
extern bool SLSWindowIteratorIsInSpace(CFTypeRef iterator, uint64_t space_id);
extern uint64_t SLSWindowIteratorGetMatchingSpaceID(CFTypeRef iterator,
    uint64_t set_mask, uint64_t type_mask,
    uint64_t *out_attributes, uint32_t *out_type, uint64_t *out_extra);
extern uint32_t SLSWindowIteratorGetSpaceAttributes(CFTypeRef iterator);
extern uint32_t SLSWindowIteratorGetSpaceTypeMask(CFTypeRef iterator);
extern int SLSWindowIteratorGetSpaceCount(CFTypeRef iterator);
extern CFArrayRef SLSWindowIteratorCopySpaces(CFTypeRef iterator);
extern uint32_t SLSWindowIteratorGetOwner(CFTypeRef iterator);
extern pid_t SLSWindowIteratorGetPID(CFTypeRef iterator);
extern ProcessSerialNumber SLSWindowIteratorGetPSN(CFTypeRef iterator);
extern CGRect SLSWindowIteratorGetBounds(CFTypeRef iterator);
extern CGRect SLSWindowIteratorGetFrameBounds(CFTypeRef iterator);
extern CGRect SLSWindowIteratorGetLastNonEmptyFrameBounds(CFTypeRef iterator);
extern CFArrayRef SLSWindowIteratorGetCornerRadii(CFTypeRef iterator, int offset);
extern CFArrayRef SLSWindowIteratorGetResolvedCornerRadii(CFTypeRef iterator);
extern uint32_t SLSWindowIteratorGetCornerMaskFlags(CFTypeRef iterator);
extern CFStringRef SLSWindowIteratorCopyTitle(CFTypeRef iterator);
extern float SLSWindowIteratorGetAlpha(CFTypeRef iterator);
extern CGRect SLSWindowIteratorGetScreenRect(CFTypeRef iterator);
extern void SLSWindowIteratorGetConstraints(CFTypeRef iterator, CGSize *outA, CGSize *outB, CGSize *outC, CGSize *junk);
extern CGError SLSGetOnscreenWindowBounds(int cid, uint32_t wid, CGRect *outRect);
extern int SLSWindowIteratorGetAttachedWindowCount(CFTypeRef iterator);
extern CFArrayRef SLSWindowIteratorCopyAttachedWindows(CFTypeRef iterator);
extern CFTypeID SLSWindowIteratorGetTypeID(CFTypeRef iterator);
extern bool SLSSpaceIteratorAdvance(CFTypeRef iterator);
extern int SLSSpaceIteratorGetCount(CFTypeRef iterator);
extern uint64_t SLSSpaceIteratorGetSpaceID(CFTypeRef iterator);
extern int SLSSpaceIteratorGetType(CFTypeRef iterator);
extern uint64_t SLSSpaceIteratorGetAttributes(CFTypeRef iterator);
extern int SLSSpaceIteratorGetAbsoluteLevel(CFTypeRef iterator);
extern uint64_t SLSSpaceIteratorGetParentSpaceID(CFTypeRef iterator);
extern OSStatus _SLPSGetCurrentProcess(ProcessSerialNumber *psn);
extern OSStatus SLPSGetKeyFocusProcess(ProcessSerialNumber *psn, uint8_t *fallback_flag);
extern pid_t SLPSGetTypingFocusProcess(void);
extern OSStatus SLPSGetNextProcess(ProcessSerialNumber *psn);
extern OSStatus SLPSGetNextToFrontProcess(ProcessSerialNumber *psn);
extern CGError SLPSGetWindowOwner(uint32_t wid, ProcessSerialNumber *psn);
extern CGError SLPSGetWindowPresenter(uint32_t wid, ProcessSerialNumber *psn);
extern CGError SLPSGetKeyBinding(int index, int32_t *outA, int32_t *outB);
extern OSStatus SLPSPBGetProcessInfo(const ProcessSerialNumber *psn, void *info);
extern OSStatus SLPSGetProcessInfo(const ProcessSerialNumber *psn, void *info);
extern CFDictionaryRef SLPSProcessInformationCopyDictionary(const ProcessSerialNumber *psn);
extern CGError SLSSetFrontProcessWithInfo(ProcessSerialNumber *psn, uint32_t wid, uint32_t options, CFDictionaryRef info);
extern CGError SLSSetFrontWindow(int cid, uint32_t wid);
extern CGError SLSSetWindowHasKeyAppearance(int cid, uint32_t wid, bool has_key);
extern CGError SLSOrderFrontConditionally(int cid, uint32_t wid, int flag);
extern int _LSSetFrontApplicationLong(int sessionID, uint32_t asn_high, uint32_t asn_low, CFDictionaryRef options);
extern CGError _CPSSetFrontProcessWithOptions(ProcessSerialNumber *psn, uint32_t wid, uint32_t opts);
extern void SLSTransactionSetMenuBarSystemOverrideAlpha(CFTypeRef transaction, uint64_t display, float alpha);
extern void SLSTransactionSpaceRebuildMenuBar(CFTypeRef transaction, uint64_t sid, int front_connection);
extern void SLSTransactionUpdateRegion(CFTypeRef transaction, CFTypeRef region);
extern CGError SLSTransactionSetWindowLockedBounds(CFTypeRef transaction, uint32_t wid, CGRect bounds);
extern CGError SLSTransactionClearWindowLockedBounds(CFTypeRef transaction, uint32_t wid);
extern CGError SLSTransactionSetWindowLockedBoundsAtPlace(CFTypeRef transaction, uint32_t wid, int place, CGRect bounds);
extern CGError SLSTransactionClearWindowLockedBoundsAtPlace(CFTypeRef transaction, uint32_t wid, int place);
extern CGError SLSTransactionMoveWindowForServerSideDrag(CFTypeRef transaction, uint32_t wid, int seq, CGRect bounds);
extern CGError SLSTransactionMoveWindowWithGroup(CFTypeRef transaction, uint32_t wid, CGPoint *point);
extern CGError SLSTransactionSetWindowShape(CFTypeRef transaction, uint32_t wid, float x_offset, float y_offset, CFTypeRef shape);
extern int SLSPostBroadcastNotification(int cid, void *data, int length);
extern int      SLSGetWindowWorkspace(int cid, uint32_t wid);
extern void SLSGetRealtimeDisplayInfoShmem(void);
extern mach_timebase_info_data_t SLSGetWindowServerTimebase(void);
extern uint64_t SLSDisplayGetPriorVBLTimeInNanoseconds(uint32_t display_id);
extern uint64_t SLSDisplayGetCurrentVBLDeltaInNanoseconds(uint32_t display_id);
extern int SLSDisplayGetRefreshTiming(uint32_t display_id, uint64_t *interval, uint64_t *timestamp);
extern int SLSDisplayGetTiming(uint32_t display_id, int timing_mode, bool suppress_errors);
extern int SLSDisplaysCurrentState(uint32_t *state_output);
extern bool SLSIsDisplayModeProMotion(uint32_t display_id, int mode_index);
extern bool SLSIsDisplayModeVRR(uint32_t display_id, int mode_index);
extern int SLSIsDisplayModeLinkMode(uint32_t display_id, int mode_index, bool *is_link_mode);
extern int SLSGetDisplayModeMinRefreshRate(uint32_t display_id, int mode_index, int32_t *min_refresh_rate);
extern int SLSDisplayStatusQuery(uint32_t display_id, int query_type);

#define kLSDefaultSessionID (-2)
